spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/jpashop?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul"
        username: root
        password: 1111
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                #        show_sql: true
                format_sql: true
                default_batch_fetch_size: 100

    messages:
        basename: messages,config.i18n.messages,errors

logging:
    level:
        org.hibernate.SQL: debug
        org.apache.coyote.http11: debug
#    org.hibernate.type: trace
